"""add product_images table

Revision ID: 07febe228035
Revises: 1ad0b4974fbf
Create Date: 2025-09-18 13:08:21.764850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07febe228035'
down_revision = '1ad0b4974fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.LargeBinary(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('digest', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_digest'), ['digest'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_digest'))

    op.drop_table('product_images')
    # ### end Alembic commands ###
