"""add must_reset_password field

Revision ID: 0addc84bde1d
Revises: 45c2a1639274
Create Date: 2025-10-03 15:33:37.085714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0addc84bde1d'
down_revision = '45c2a1639274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_reset_password', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('must_reset_password')

    # ### end Alembic commands ###
