"""password a 255 y unique parcial payment_id en orders

Revision ID: 12bb607c34a4
Revises: 9e6f7ad18a86
Create Date: 2025-09-27 14:25:58.240908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bb607c34a4'
down_revision = '9e6f7ad18a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_payment_id'), ['payment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_payment_id'))

    # ### end Alembic commands ###
