"""Add brand field to Product model

Revision ID: 200041153e0b
Revises: 8babe001ac6b
Create Date: 2025-09-05 12:03:45.752605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200041153e0b'
down_revision = '8babe001ac6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
