"""add dni + billing/shipping_address to User; flavor fields y extras a Product

Revision ID: 31907efa209d
Revises: 04db8361768d
Create Date: 2025-09-16 11:00:36.433340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31907efa209d'
down_revision = '04db8361768d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('dni')

    # ### end Alembic commands ###
