"""selected falvor agregado

Revision ID: 45c2a1639274
Revises: 12bb607c34a4
Create Date: 2025-09-30 11:08:10.969344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c2a1639274'
down_revision = '12bb607c34a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_flavor', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('selected_flavor')

    # ### end Alembic commands ###
