"""add tracking_code to Order

Revision ID: 796fbe860a5e
Revises: e7777834fb9c
Create Date: 2025-10-10 13:48:22.197460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796fbe860a5e'
down_revision = 'e7777834fb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_code', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('tracking_code')

    # ### end Alembic commands ###
