"""add short_description to product

Revision ID: 82e33fe0bd93
Revises: c4582a534709
Create Date: 2025-09-10 11:29:14.585957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e33fe0bd93'
down_revision = 'c4582a534709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('flavor_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('flavor_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
