"""Add is_admin field to User model

Revision ID: 8babe001ac6b
Revises: dc86759bb6f4
Create Date: 2025-09-05 12:00:25.312485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8babe001ac6b'
down_revision = 'dc86759bb6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna como nullable primero
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # Actualizar todos los usuarios existentes a is_admin=False
    op.execute("UPDATE \"user\" SET is_admin = false WHERE is_admin IS NULL")
    
    # Cambiar la columna a NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
