"""product_images ON DELETE CASCADE

Revision ID: 9e6f7ad18a86
Revises: 07febe228035
Create Date: 2025-09-20 12:44:38.860359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6f7ad18a86'
down_revision = '07febe228035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index('ix_product_images_product_id', ['product_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('product_images_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_images_product_id_fkey'), 'product', ['product_id'], ['id'])
        batch_op.drop_index('ix_product_images_product_id')

    # ### end Alembic commands ###
