"""Add puffs, nicotine and volume fields to Product

Revision ID: 9f352dd99308
Revises: 610373df213c
Create Date: 2025-09-09 12:02:53.101332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f352dd99308'
down_revision = '610373df213c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puffs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nicotine_mg', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('volume_ml', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('volume_ml')
        batch_op.drop_column('nicotine_mg')
        batch_op.drop_column('puffs')

    # ### end Alembic commands ###
