"""Ampliar tamaños de name, description y short_description

Revision ID: c3730afbd2fd
Revises: f4ca8b0f894d
Create Date: 2025-09-11 13:38:20.684473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3730afbd2fd'
down_revision = 'f4ca8b0f894d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=4000),
               existing_nullable=True)
        batch_op.alter_column('short_description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=4000),
               existing_nullable=True)
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('brand',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('short_description',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
