"""Add MercadoPago fields to Order model

Revision ID: f4ca8b0f894d
Revises: 82e33fe0bd93
Create Date: 2025-09-10 16:34:39.282059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ca8b0f894d'
down_revision = '82e33fe0bd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('external_reference')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
